=== acatalas/Tasca1-LunarLander/LunarLander_CSV/src/conf/xml-resources/jaxb/Configuracions/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" elementFormDefault="qualified">
  <xs:element name="configuraciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="configuracion" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="nave" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="modoDificil" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
          </xs:sequence>
          <xs:attribute name="nombre" type="xs:string" use="required"/>
        </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== acatalas/Tasca1-LunarLander/LunarLander_CSV/web/xml/config.xml
<?xml version='1.0' encoding='UTF-8'?>
<configuraciones xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='file:///C:/Users/Ale/Documents/NetBeansProjects/JAXBReader/config.xsd'>
    <configuracion nombre='RD'>
        <nave>Rojo</nave>
        <modoDificil>true</modoDificil>
    </configuracion>
    <configuracion nombre='BD'>
        <nave>Blanco</nave>
        <modoDificil>true</modoDificil>
    </configuracion>
    <configuracion nombre='RF'>
        <nave>Rojo</nave>
        <modoDificil>false</modoDificil>
    </configuracion>
    <configuracion nombre='BF'>
        <nave>Blanco</nave>
        <modoDificil>false</modoDificil>
    </configuracion>
    <configuracion nombre='LF'>
        <nave>Lila</nave>
        <modoDificil>false</modoDificil>
    </configuracion>
    <configuracion nombre='LD'>
        <nave>Lila</nave>
        <modoDificil>true</modoDificil>
    </configuracion>
</configuraciones>
